export const productOptions = {
  Others: {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  IFPD: {
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch", "110 inch"],
    specs: [
      "Android 9, 4GB RAM, 32GB ROM",
      "Android 8, 4GB RAM, 32GB ROM",
      "Android 11, 4GB RAM, 32GB ROM",
      "Android 11, 4GB RAM, 64GB ROM",
      "Android 11, 8GB RAM, 128GB ROM",
      "Android 12, 4GB RAM, 32GB ROM",
      "Android 13, 4GB RAM, 32GB ROM",
      "Android 13, 8GB RAM, 128GB ROM",
      "Android 13, 8GB RAM, 128GB ROM  Inbuilt Camera",
      "Android 14, 8GB RAM, 128GB ROM",
      "Android 14, 8GB RAM, 128GB ROM Inbuilt Camera",
      "EDLA Android 14, 8GB RAM, 128GB ROM",
      "EDLA Android 14, 8GB RAM, 128GB ROM Inbuilt Camera",
    ],
  },
  OPS: {
    sizes: ["N/A"],
    specs: [
      // i5 4th Gen
      "i5 4th Gen, 8GB RAM, 256GB ROM",
      "i5 4th Gen, 8GB RAM, 512GB ROM",

      // i5 10th Gen
      "i5 10th Gen, 8GB RAM, 256GB ROM",
      "i5 10th Gen, 8GB RAM, 512GB ROM",
      "i5 10th Gen, 8GB RAM, 1TB ROM",
      "i5 10th Gen, 16GB RAM, 256GB ROM",
      "i5 10th Gen, 16GB RAM, 512GB ROM",
      "i5 10th Gen, 16GB RAM, 1TB ROM",

      // i5 11th Gen
      "i5 11th Gen, 8GB RAM, 256GB ROM",
      "i5 11th Gen, 8GB RAM, 512GB ROM",
      "i5 11th Gen, 8GB RAM, 1TB ROM",
      "i5 11th Gen, 16GB RAM, 256GB ROM",
      "i5 11th Gen, 16GB RAM, 512GB ROM",
      "i5 11th Gen, 16GB RAM, 1TB ROM",

      // i5 12th Gen
      "i5 12th Gen, 8GB RAM, 256GB ROM",
      "i5 12th Gen, 8GB RAM, 512GB ROM",
      "i5 12th Gen, 8GB RAM, 1TB ROM",
      "i5 12th Gen, 16GB RAM, 256GB ROM",
      "i5 12th Gen, 16GB RAM, 512GB ROM",
      "i5 12th Gen, 16GB RAM, 1TB ROM",

      // i7 11th Gen
      "i7 11th Gen, 8GB RAM, 256GB ROM",
      "i7 11th Gen, 8GB RAM, 512GB ROM",
      "i7 11th Gen, 8GB RAM, 1TB ROM",
      "i7 11th Gen, 16GB RAM, 256GB ROM",
      "i7 11th Gen, 16GB RAM, 512GB ROM",
      "i7 11th Gen, 16GB RAM, 1TB ROM",

      // i7 12th Gen
      "i7 12th Gen, 8GB RAM, 256GB ROM",
      "i7 12th Gen, 8GB RAM, 512GB ROM",
      "i7 12th Gen, 8GB RAM, 1TB ROM",
      "i7 12th Gen, 16GB RAM, 256GB ROM",
      "i7 12th Gen, 16GB RAM, 512GB ROM",
      "i7 12th Gen, 16GB RAM, 1TB ROM",
    ],
  },

  "Digital Podium": {
    sizes: ["Standard"],
    specs: [
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 2 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
    ],
  },
  "Advance Digital Podium": {
    sizes: [
      "Standard",
      "Front Display 32inch, RAM 4 GB, ROM 128 GB, Processor i5",
      "Front Display 32inch, RAM 4 GB, ROM 128 GB, Processor i7",
      "Front Display 32inch, RAM 4 GB, ROM 256 GB, Processor i5",
      "Front Display 32inch, RAM 4 GB, ROM 256 GB, Processor i7",
      "Front Display 32inch, RAM 4 GB, ROM 512 GB, Processor i5",
      "Front Display 32inch, RAM 4 GB, ROM 512 GB, Processor i7",
      "Front Display 32inch, RAM 4 GB, ROM 1024 GB, Processor i5",
      "Front Display 32inch, RAM 4 GB, ROM 1024 GB, Processor i7",
    ],
    specs: [
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 2 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
    ],
  },
  "Audio Podium": { sizes: ["Full"], specs: ["N/A"] },
  Kiosk: {
    sizes: ["22 inch", "32 inch", "43 inch", "55 inch", "65 inch"],
    specs: [
      "Touch Andriod 13/4/32",
      "Non-Touch Andriod 13/4/32",
      "Windows 10 OS 16/256/i5",
    ],
  },
  Adapter: { sizes: ["N/A"], specs: ["N/A"] },
  "PTZ Camera": {
    sizes: ["N/A"],
    specs: [
      "Non-Voice Tracking-Full HD",
      "PRO 3008: 20X, Voice Tracking, Gesture Control, 30fps, USB 3.0",
      "PRO 500V: 20X, 4K, Voice Tracking, Gesture Control, 60fps, USB 3.0",
    ],
  },
  "Document Camera": {
    sizes: ["N/A"],
    specs: [
      "Hydraulic Wall Mount Visualizer",
      "Visualizer",
    ],
  },
  UPS: {
    sizes: ["Standard"],
    specs: ["1 KVA"],
  },
  "Wallmount Kit": {
    sizes: ["55 inch", "65 inch", "75 inch", "86 inch", "98 inch"],
    specs: ["Standard"],
  },
  "Stylus Pen": { sizes: ["N/A"], specs: ["N/A"] },
  "Dual sliding shutter": { sizes: ["65 inch", "75 inch", "86 inch", "98 inch"],
    specs: [
      "Common",
      "White Writing Board & Blue Display Board",
      "White Writing Board & Red Display Board",
      "White Writing Board & Green Display Board",
      "Green Writing Board & Blue Display Board",
      "Both Side Main & Display Green Writing Board",
      "Both Side Main & Display White Writing Board",
      "White Writing Board (Main) & Green Writing Board (Display)",
      "One White Writing & One Green Writing Board with red display board",
    ], },
  "Single Sliding Shutter": {
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch"],
    specs: [
      "Common",
      "White Writing Board & Blue Display Board",
      "White Writing Board & Red Display Board",
      "White Writing Board & Green Display Board",
      "Green Writing Board & Blue Display Board",
      "Both Side Main & Display Green Writing Board",
      "Both Side Main & Display White Writing Board",
      "White Writing Board (Main) & Green Writing Board (Display)",
      "One White Writing & One Green Writing Board with red display board",
    ],
  },
  "3 Cup Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  "4 Cup Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  Microphone: {
    sizes: ["N/A"],
    specs: ["Handheld Collar Mic", "Goose Neck Mic", "Collar/Lapel Mic"],
  },
  "Wireless Speaker Phone": {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  CCTV: {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  Keyboard: {
    sizes: ["N/A"],
    specs: ["Wireless", "Wired"],
  },
  "LED Display Controller": {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  "Aluminium Profile Frame for LED Display": {
    sizes: ["N/A"],
    specs: ["N/A"],
  },
  "NVR 16 CHANNEL": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "2 MP CAMERA IP CP PLUS": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "BULLET/DOM": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "8 Port POE SWITCH": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "HARD DISK": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  BOX: {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "Cat6e CABLE": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "PVC RACK": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "POWER CABLE": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  RACK: {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },
  "Conduit PIPE": {
    sizes: ["N/A"],
    specs: ["AS PER SPEC"],
  },

  "White board": {
    sizes: ["3x4", "6x4"],
    specs: ["AS PER SPEC"],
  },
  "FABRIC pin up board": {
    sizes: ["3x4"],
    specs: ["AS PER SPEC"],
  },
  Mouse: {
    sizes: ["N/A"],
    specs: ["Wireless", "Wired"],
  },
  "Interactive White Board": {
    sizes: ["82 inch"],
    specs: ["Ceramic", "Non-Ceramic"],
  },
  "Floor Stand": { sizes: ["N/A"], specs: ["N/A"] },
  "Notice Board": { sizes: ["N/A"], specs: ["N/A"] },
  Visualizer: { sizes: ["N/A"], specs: ["N/A"] },
  "Web Cam": {
    sizes: ["N/A"],
    specs: ["Full HD Non-AI Featured", "4K AI Featured", "4K Auto Tracking"],
  },
  "Bluetooth Microphone": { sizes: ["N/A"], specs: ["N/A"] },
  "UPS Cabinet": { sizes: ["N/A"], specs: ["N/A"] },
  "SD Card": {
    sizes: ["N/A"],
    specs: ["8GB", "16GB", "32GB", "64GB", "128GB"],
  },
  Casing: { sizes: ["N/A"], specs: ["N/A"] },
  "Fitting Accessories": { sizes: ["N/A"], specs: ["N/A"] },
  "HDMI Cable": {
    sizes: ["N/A"],
    specs: ["Standard", "4K"],
  },
  "C-type Cable": { sizes: ["N/A"], specs: ["N/A"] },
  "Fujifilm-Printer": {
    sizes: ["A3", "A4", "Legal"],
    specs: [
      "Color Printer",
      "Monochrome Printer",
      "MFM Color",
      "MFM Monochrome",
    ],
  },
  "Google TV": {
    sizes: ["43 inch", "50 inch", "55 inch", "75 inch","86 inch"],
    specs: ["4GB RAM / 32GB ROM 4K"],
  },
  "Wriety Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Ceiling Mount Kit": {
    sizes: ["Standard"],
    specs: ["Projector Ceiling Mount", "PTZ Ceiling Mount"],
  },
  "Almirah Type Shutter": {
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch"],
    specs: ["Plain", "White Boards", "Green Boards"],
  },
   "K-12 Content": {
    sizes: ["Standard"],
    specs: ["Standard"],
  },
  Aicharya: {
    sizes: ["N/A"],
    specs: ["Standard"],
  },
  TripodStand: {
    sizes: ["N/A"],
    specs: ["Standard"],
  },
  Logo: { sizes: ["N/A"], specs: ["N/A"] },
  Microphones: { sizes: ["N/A"], specs: ["N/A"] },
  "E-Share License": { sizes: ["N/A"], specs: ["N/A"] },
  "PRO Share Software": { sizes: ["N/A"], specs: ["N/A"] },
  "E Share Software": { sizes: ["N/A"], specs: ["N/A"] },
  "DMS Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Battery Bank": { sizes: ["N/A"], specs: ["N/A"] },
  "Rack & Interlink": { sizes: ["N/A"], specs: ["N/A"] },
  "Wooden Podium": { sizes: ["N/A"], specs: ["N/A"] },
  "LED Video Wall Indoor": { sizes: ["N/A"], specs: ["N/A"] },
  "LED Video Wall Outdoor": { sizes: ["N/A"], specs: ["N/A"] },
  "4K Video Bar": { sizes: ["N/A"], specs: ["N/A"] },
  "Microsoft Office 2016 Licensed": { sizes: ["N/A"], specs: ["N/A"] },
  "Windows 11 Licensed": { sizes: ["N/A"], specs: ["N/A"] },
  "Embibe Content": { sizes: ["N/A"], specs: ["N/A"] },
  SSD: {
    sizes: ["N/A"],
    specs: ["256GB", "512GB", "1TB"],
  },
  RAM: {
    sizes: ["N/A", "65"],
    specs: ["8GB", "16GB", "RSP"],
  },
  "CBSE Content": { sizes: ["N/A"], specs: ["N/A"] },
  "PA System Speakers": { sizes: ["N/A"], specs: ["N/A"] },
  "Promark Stickers": { sizes: ["N/A"], specs: ["N/A"] },
  "3 Cup Conference Speaker": { sizes: ["N/A"], specs: ["N/A"] },
  Content: { sizes: ["N/A"], specs: ["N/A"] },
  Flex: { sizes: ["N/A"], specs: ["N/A"] },
  "Wireless Speakerphone - Two Pair": { sizes: ["N/A"], specs: ["N/A"] },
  Remote: { sizes: ["N/A"], specs: ["N/A"] },
  "Educational Software": { sizes: ["N/A"], specs: ["N/A"] },
  "Hydraulic Bracket": { sizes: ["N/A"], specs: ["N/A"] },
  "Desktop PC Monitor": { sizes: ["N/A"], specs: ["N/A"] },
  "Home Theatre": { sizes: ["N/A"], specs: ["N/A"] },
  "Digital Audio Processor": { sizes: ["N/A"], specs: ["N/A"] },
  Projector: {
    sizes: ["N/A"],
    specs: ["Long Throw", "Short Throw", "Ultra Long Throw"],
  },
  "LED TV": {
    sizes: ["32 inch", "43 inch", "55 inch", "65 inch"],
    specs: ["N/A"],
  },
  "Digital Podium Controller": { sizes: ["N/A"], specs: ["N/A"] },
  "Amplifier Mic Receiver": { sizes: ["N/A"], specs: ["N/A"] },
  "Wireless Mic Receiver": { sizes: ["N/A"], specs: ["N/A"] },
  "Projector Screen": { sizes: ["N/A"], specs: ["N/A"] },
  Speakerphone: { sizes: ["N/A"], specs: ["N/A"] },
  "Bubble Roll": { sizes: ["N/A"], specs: ["N/A"] },
  "Wrapping Roll": { sizes: ["N/A"], specs: ["N/A"] },
  "Microphone Stand": {
    sizes: ["N/A"],
    specs: [
      "Type: Floor Stand, Height: 690-1000mm, Base Dia: 230mm, Weight: Not Less Than 3Kg",
    ],
  },
  "Desktop Computer": {
    sizes: ["24 inch Monitor"],
    specs: [
      "Processor: i5 12th Gen, RAM: 16GB, Storage: 512GB SSD, OS: Windows 11, Software: Office 2021, Features: Inbuilt WiFi, Keyboard, Mouse",
    ],
  },
};

export const statesAndCities = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Jaganathpuram",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Kurnool",
    "Rajahmundry",
    "Nellore",
    "Anantapur",
    "Kadapa",
    "Srikakulam",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Proddatur",
    "Machilipatnam",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Tawang",
    "Ziro",
    "Pasighat",
    "Bomdila",
    "Naharlagun",
    "Roing",
    "Aalo",
    "Tezu",
    "Changlang",
    "Khonsa",
    "Yingkiong",
    "Daporijo",
    "Seppa",
  ],
  Assam: [
    "Agartala",
    "Tripura",
    "Guwahati",
    "Dibrugarh",
    "Jorhat",
    "Silchar",
    "Tezpur",
    "Tinsukia",
    "Nagaon",
    "Sivasagar",
    "Barpeta",
    "Goalpara",
    "Karimganj",
    "Lakhimpur",
    "Diphu",
    "Golaghat",
    "Kamrup",
  ],
  Bihar: [
    "Chapra",
    "Siwan",
    "Gopalganj",
    "Bettiah",
    "Motihari",
    "Sitamarhi",
    "Sheohar",
    "Darbhanga",
    "Madhubani",
    "Samastipur",
    "Vaishali",
    "Muzaffarpur",
    "Madhepura",
    "Khagaria",
    "Begusrai",
    "Lakhisrai",
    "Munger",
    "Jamui",
    "Banka",
    "Bhagalpur",
    "Katihar",
    "Purnia",
    "Araria",
    "Kishanganj",
    "Patna",
    "Bhojpur/Arah",
    "Buxar",
    "Rohtas/Sasaram",
    "Kaimur",
    "Aurangabad",
    "Arwal",
    "Jehanabad",
    "Nawada",
    "Sheikhpura",
    "Gaya",
    "Barh",
    "Nalanda",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Korba",
    "Bhilai",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Dhamtari",
    "Kawardha",
    "Mahasamund",
    "Kondagaon",
    "Bijapur",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Sanguem",
    "Canacona",
    "Quepem",
    "Valpoi",
    "Sanquelim",
    "Curchorem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Morbi",
    "Nadiad",
    "Porbandar",
    "Mehsana",
    "Bharuch",
    "Navsari",
    "Surendranagar",
  ],
  Haryana: [
    "Bahadurgarh",
    "Charkhi Dadri",
    "Panchkula",
    "Gurugram",
    "Faridabad",
    "Tohna",
    "Panipat",
    "Ambala",
    "Palwal",
    "Hisar",
    "Rohtak",
    "Karnal",
    "Bhiwani",
    "Kaithal",
    "Kurukshetra",
    "Sonipat",
    "Jhajjar",
    "Jind",
    "Fatehabad",
    "Pehowa",
    "Pinjore",
    "Rewari",
    "Yamunanagar",
    "Sirsa",
    "Dabwali",
    "Narwana",
    "Mahendragarh",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul and Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una",
  ],
  Jharkhand: [
    "Ranchi",
    "Koderma",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Palamu",
    "Gumla",
    "Lohardaga",
    "Dumka",
    "Chatra",
    "Pakur",
    "Jamtara",
    "Simdega",
    "Sahibganj",
    "Godda",
    "Latehar",
    "Khunti",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Kalaburagi",
    "Ballari",
    "Davangere",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Vijayapura",
    "Chikkamagaluru",
    "Hassan",
    "Mandya",
    "Raichur",
    "Bidar",
    "Bagalkot",
    "Chitradurga",
    "Kolar",
    "Gadag",
    "Yadgir",
    "Haveri",
    "Dharwad",
    "Ramanagara",
    "Chikkaballapur",
    "Kodagu",
    "Koppal",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kannur",
    "Alappuzha",
    "Thrissur",
    "Kottayam",
    "Palakkad",
    "Ernakulam",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Kollam",
    "Kasaragod",
    "Punalur",
    "Varkala",
    "Changanassery",
    "Kayani",
    "Kizhakkambalam",
    "Perumbavoor",
    "Muvattupuzha",
    "Attingal",
    "Vypin",
    "North Paravur",
    "Adoor",
    "Cherthala",
    "Mattancherry",
    "Fort Kochi",
    "Munroe Island",
  ],
  "Madhya Pradesh": [
    "Shajapur",
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Ratlam",
    "Satna",
    "Dewas",
    "Murwara (Katni)",
    "Chhindwara",
    "Rewa",
    "Burhanpur",
    "Khandwa",
    "Bhind",
    "Shivpuri",
    "Vidisha",
    "Sehore",
    "Hoshangabad",
    "Itarsi",
    "Neemuch",
    "Chhatarpur",
    "Betul",
    "Mandsaur",
    "Damoh",
    "Singrauli",
    "Guna",
    "Ashok Nagar",
    "Datia",
    "Mhow",
    "Pithampur",
    "Shahdol",
    "Seoni",
    "Mandla",
    "Tikamgarh",
    "Raisen",
    "Narsinghpur",
    "Morena",
    "Barwani",
    "Rajgarh",
    "Khargone",
    "Anuppur",
    "Umaria",
    "Dindori",
    "Sheopur",
    "Alirajpur",
    "Jhabua",
    "Sidhi",
    "Harda",
    "Balaghat",
    "Agar Malwa",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Thane",
    "Satara",
    "Latur",
    "Chandrapur",
    "Jalgaon",
    "Bhiwandi",
    "Shirdi",
    "Akola",
    "Parbhani",
    "Raigad",
    "Washim",
    "Buldhana",
    "Nanded",
    "Yavatmal",
    "Beed",
    "Amravati",
    "Kalyan",
    "Dombivli",
    "Ulhasnagar",
    "Nagothane",
    "Vasai",
    "Virar",
    "Mira-Bhayandar",
    "Dhule",
    "Sangli",
    "Wardha",
    "Ahmednagar",
    "Pandharpur",
    "Malegaon",
    "Osmanabad",
    "Gondia",
    "Baramati",
    "Jalna",
    "Hingoli",
    "Sindhudurg",
    "Ratnagiri",
    "Palghar",
    "Ambarnath",
    "Badlapur",
    "Taloja",
    "Alibaug",
    "Murbad",
    "Karjat",
    "Pen",
    "Newasa",
  ],
  Manipur: [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Bishnupur",
    "Kakching",
    "Senapati",
    "Ukhrul",
    "Tamenglong",
    "Jiribam",
    "Moreh",
    "Noney",
    "Pherzawl",
    "Kangpokpi",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Cherrapunjee",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Mawkyrwat",
    "Resubelpara",
    "Mairang",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Saiha",
    "Lawngtlai",
    "Mamit",
    "Hnahthial",
    "Khawzawl",
    "Saitual",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Mon",
    "Zunheboto",
    "Phek",
    "Longleng",
    "Kiphire",
    "Peren",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Puri",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Jeypore",
    "Angul",
    "Dhenkanal",
    "Keonjhar",
    "Kendrapara",
    "Jagatsinghpur",
    "Paradeep",
    "Bargarh",
    "Rayagada",
    "Koraput",
    "Nabarangpur",
    "Kalahandi",
    "Nuapada",
    "Phulbani",
    "Balangir",
    "Sundargarh",
  ],
  Punjab: [
    "Amritsar",
    "Bathinda",
    "Barnala",
    "Derabassi",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Lodhipur",
    "Ferozepur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "S.A.S. Nagar",
    "Sangrur",
    "Shaheed Bhagat Singh Nagar",
    "Sri Muktsar Sahib",
    "Tarn Taran",
  ],
  Rajasthan: [
    "Sri Ganganagar",
    "Hanumangarh",
    "Churu",
    "Jhunjhunu",
    "Sikar",
    "Deedwana Kuchaman",
    "Nagaur",
    "Bikaner",
    "Phalodi",
    "Jaisalmer",
    "Barmer",
    "Balotra",
    "Jodhpur",
    "Pali",
    "Jalore",
    "Sirohi",
    "Udaipur",
    "Salumber",
    "Dungarpur",
    "Banswara",
    "Pratapgarh",
    "Chittorgarh",
    "Rajsamand",
    "Bhilwara",
    "Ajmer",
    "Beawar",
    "Tonk",
    "Bundi",
    "Kota",
    "Baran",
    "Jhalawar",
    "Jaipur",
    "Dausa",
    "Sawai Madhopur",
    "Karauli",
    "Dholpur",
    "Bharatpur",
    "Deeg",
    "Alwar",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Pelling",
    "Geyzing",
    "Mangan",
    "Rangpo",
    "Jorethang",
    "Yuksom",
    "Ravangla",
    "Lachen",
    "Lachung",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thanjavur",
    "Tuticorin",
    "Dindigul",
    "Cuddalore",
    "Kancheepuram",
    "Nagercoil",
    "Kumbakonam",
    "Karur",
    "Sivakasi",
    "Namakkal",
    "Tiruppur",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Ramagundam",
    "Siddipet",
    "Adilabad",
    "Nalgonda",
    "Mancherial",
    "Kothagudem",
    "Zaheerabad",
    "Miryalaguda",
    "Bhongir",
    "Jagtial",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Kamalpur",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Sonamura",
    "Melaghar",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Bulandshahr",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahar",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Greater Noida",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kushi Nagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffar Nagar",
    "Noida",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharth Nagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Rishikesh",
    "Mussoorie",
    "Almora",
    "Pithoragarh",
    "Haldwani",
    "Rudrapur",
    "Bageshwar",
    "Champawat",
    "Uttarkashi",
    "Roorkee",
    "Tehri",
    "Lansdowne",
  ],
  "West Bengal": [
    "Kolkata",
    "Garia",
    "Darjeeling",
    "Siliguri",
    "Howrah",
    "Asansol",
    "Durgapur",
    "Malda",
    "Cooch Behar",
    "Haldia",
    "Kharagpur",
    "Raiganj",
    "Bardhaman",
    "Jalpaiguri",
    "Chandannagar",
    "Kalimpong",
    "Alipurduar",
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Havelock Island",
    "Diglipur",
    "Neil Island",
    "Car Nicobar",
    "Little Andaman",
    "Long Island",
    "Mayabunder",
    "Campbell Bay",
    "Rangat",
    "Wandoor",
  ],
  Chandigarh: [
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 7",
    "Sector 8",
    "Sector 9",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Amli",
    "Kachigam",
    "Naroli",
    "Vapi",
    "Marwad",
    "Samarvarni",
    "Kawant",
  ],
  Delhi: [
    "New Delhi",
    "Rani Bagh",
    "Shalimar Bagh",
    "Tilak Nagar",
    "Hari Nagar Dadb",
    "Hari Nagar",
    "Maya Puri",
    "Alaknanda",
    "Old Delhi",
    "Dwarka",
    "Rohini",
    "Karol Bagh",
    "Lajpat Nagar",
    "Saket",
    "Vasant Kunj",
    "Janakpuri",
    "Mayur Vihar",
    "Shahdara",
    "Preet Vihar",
    "Pitampura",
    "Chanakyapuri",
    "Narela",
    "Mehrauli",
    "Najafgarh",
    "Okhla",
    "Tilak Nagar",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],
  Ladakh: [
    "Leh",
    "Kargil",
    "Diskit",
    "Padum",
    "Nubra",
    "Tangtse",
    "Sankoo",
    "Zanskar",
    "Nyoma",
    "Turtuk",
    "Hanle",
  ],
  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Amini",
    "Andrott",
    "Kalpeni",
    "Kadmat",
    "Chetlat",
    "Bitra",
    "Bangaram",
  ],
  Puducherry: [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam",
    "Villianur",
    "Bahour",
    "Oulgaret",
    "Ariyankuppam",
    "Nettapakkam",
  ],
};

export const orderTypeOptions = [
  "B2G",
  "B2C",
  "B2B",
  "Demo",
  "Replacement",
  "Stock Out",
  "Repair",
];
export const companyOptions = ["Promark", "Foxmate", "Promine", "Primus"];

export const paymentMethodOptions = ["Cash", "NEFT", "RTGS", "Cheque"];
export const paymentTermsOptions = [
  "100% Advance",
  "Partial Advance",
  "Credit",
];
export const salesPersonlist = [
  { label: "Abhay Pratap Singh", value: "Abhay Pratap Singh" },
  { label: "Abhay Bhardwaj", value: "Abhay Bhardwaj" },
  { label: "Abhayjit Sekhon", value: "Abhayjit Sekhon" },
  { label: "Ajay Kumar", value: "Ajay Kumar" },
  { label: "Amarjeet Singh", value: "Amarjeet Singh" },
  { label: "Anirban Syam", value: "Anirban Syam" },
  { label: "Arif Khan", value: "Arif Khan" },
  { label: "Arwinder Singh", value: "Arwinder Singh" },
  { label: "Ashwani Kumar", value: "Ashwani Kumar" },
  { label: "Bachan Pal", value: "Bachan Pal" },
  { label: "Deepak saini", value: "Deepak saini" },
  { label: "Dinesh Soni", value: "Dinesh Soni" },
  { label: "Parth Bhardwaj", value: "Parth Bhardwaj" },
  { label: "Gursewak Singh", value: "Gursewak Singh" },
  { label: "Global", value: "Global" },
  { label: "Gem Team", value: "Gem Team" },
  { label: "Gurnam Bhullar", value: "Gurnam Bhullar" },
  { label: "Harish Kumar", value: "Harish Kumar" },
  { label: "Heena Mehra", value:"Heena Mehra"},
  { label: "Harpreet Singh", value: "Harpeet Singh" },
  { label: "J P Sharma", value: "J P Sharma" },
  { label: "Jagan Lal", value: "Jagan Lal" },
  { label: "Jyoti Rani", value: "Jyoti Rani" },
  { label: "Javvad Akram", value: "Javvad Akram" },
  { label: "Jashanpreet", value: "Jashanpreet" },
  { label: "Jai Srivastava", value: "Jai Srivastava" },
  { label: "Kulwinder Singh", value: "Kulwinder Singh" },
  { label: "Madeeha Hasan", value: "Madeeha Hasan" },
  { label: "Manjit Singh Chowhan", value: "Manjit Singh Chowhan" },
  { label: "Mayank Goutam", value: "Mayank Goutam" },
  { label: "Mukul Kubba", value: "Mukul Kubba" },
  { label: "Monika", value: "Monika" },
  { label: "Muskan", value: "Muskan" },
  { label: "Nadeem Khan", value: "Nadeem Khan" },
  { label: "Narinder Singh", value: "Narinder Singh" },
  { label: "Parmjeet Singh", value: "Parmjeet Singh" },
  { label: "Pitamber Sharma", value: "Pitamber Sharma" },
  { label: "Pihu Juneja", value: "Pihu Juneja" },
  { label: "Payal Narayan", value: "Payal Narayan" },
  { label: "Piyush Chopra", value: "Piyush Chopra" },
  { label: "PS Brar", value: "PS Brar" },
  { label: "Purnendu Kumar", value: "Purnendu Kumar" },
  { label: "Raj Bahadur Singh", value: "Raj Bahadur Singh" },
  { label: "Rajeev Kanda", value: "Rajeev Kanda" },
  { label: "Rajeev Kumar Singh", value: "Rajeev Kumar Singh" },
  { label: "Rajeev Pal Singh", value: "Rajeev Pal Singh" },
  { label: "Riya Rana", value: "Riya Rana" },
  { label: "Ramkumar Singh", value: "Ramkumar Singh" },
  { label: "Ranbeer Kaur", value: "Ranbeer Kaur" },
  { label: "Rachit Arya", value: "Rachit Arya" },
  { label: "Rahul", value: "Rahul" },
  { label: "Rohit Kumar Tiwari", value: "Rohit Kumar Tiwari" },
  { label: "Ritik Poddar", value: "Ritik Poddar" },
  { label: "Shadab Khan", value: "Shadab Khan" },
  { label: "Sahil Gupta", value: "Sahil Gupta" },
  { label: "Sahiba", value: "Sahiba" },
  { label: "Savir Khan", value: "Savir Khan" },
  { label: "Shri Kant", value: "Shri Kant" },
  { label: "Swati Sood", value: "Swati Sood" },
  { label: "Sidhant Oberai", value: "Sidhant Oberai" },
  { label: "Sidhant Prajapati", value: "Sidhant Prajapati" },
  { label: "Sukhjinder Pal Singh", value: "Sukhjinder Pal Singh" },
  { label: "Sunil Kukkar", value: "Sunil Kukkar" },
  { label: "Sunil Kumar Singh", value: "Sunil Kumar Singh" },
  { label: "Surbhi Chugh", value: "Surbhi Chugh" },
  { label: "Sushil Kumar", value: "Sushil Kumar" },
  { label: "Sukhvir Singh", value: "Sukhvir Singh" },
  { label: "Savita Mamgain", value: "Savita Mamgain" },
  { label: "Sonali Dalal", value: "Sonali Dalal" },
  { label: "Srishti Yadav", value: "Srishti Yadav" },
  { label: "Sushant Dutta", value: "Sushant Dutta" },
  { label: "Seema", value: "Seema" },
  { label: "Vageesh Bhardwaj", value: "Vageesh Bhardwaj" },
  { label: "Varun Budhiraja", value: "Varun Budhiraja" },
  { label: "Vaseem Khan", value: "Vaseem Khan" },
];

export const Reportinglist = [
  { label: "Abhay Pratap Singh", value: "Abhay Pratap Singh" },
  { label: "Abhayjit Sekhon", value: "Abhayjit Sekhon" },
  { label: "Amarjeet Singh", value: "Amarjeet Singh" },
  { label: "Arwinder Singh", value: "Arwinder Singh" },
  { label: "Ashwani Kumar", value: "Ashwani Kumar" },
  { label: "Bachan Pal", value: "Bachan Pal" },
  { label: "Gem Team", value: "Gem Team" },
  { label: "Heera Singh Daspa", value: "Heera Singh Daspa" },
  { label: "Harpreet Singh", value: "Harpeet Singh" },
  { label: "J P Sharma", value: "J P Sharma" },
  { label: "Manjit Singh Chowhan", value: "Manjit Singh Chowhan" },
  { label: "Mukul Kubba", value: "Mukul Kubba" },
  { label: "PS Brar", value: "PS Brar" },
  { label: "Priya Sharma", value: "Priya Sharma" },
  { label: "Purnendu Kumar", value: "Purnendu Kumar" },
  { label: "Raj Bahadur Singh", value: "Raj Bahadur Singh" },
  { label: "Rajeev Kanda", value: "Rajeev Kanda" },
  { label: "Rajeev Kumar Singh", value: "Rajeev Kumar Singh" },
  { label: "Rajeev Pal Singh", value: "Rajeev Pal Singh" },
  { label: "Sahil Gupta", value: "Sahil Gupta" },
  { label: "Susheel Kumar", value: "Susheel Kumar" },
  { label: "Sukhvir Singh", value: "Sukhvir Singh" },
  { label: "Savir Khan", value: "Savir Khan" },
  { label: "Siddhartha Kumar", value: "Siddhartha Kumar" },
  { label: "Sukhjinder Pal Singh", value: "Sukhjinder Pal Singh" },
  { label: "Sunil Kukkar", value: "Sunil Kukkar" },
  { label: "Surbhi Chugh", value: "Surbhi Chugh" },
  { label: "Sushil Kumar", value: "Sushil Kumar" },
  { label: "Varun Budhiraja", value: "Varun Budhiraja" },
  { label: "Vaseem Khan", value: "Vaseem Khan" },
];

export const modelNoOptions = ["AT", "PRO MR PC", "Standard"];
export const printerOptions = [
  "1 Tray Module",
  "18K toner",
  "250 sheet feeder",
  "250 Sheets Feeder Unit",
  "3 Tray Module",
  "520 sheet feeder",
  "6K toner",
  "73K drum",
  "Accessory table",
  "Adobe PostScript 3 Kit",
  "Apeos 2560",
  "Apeos 3060",
  "Apeos 3560",
  "Apeos 4570",
  "Apeos 5570",
  "Apeos C2060",
  "Apeos C2450 S",
  "Apeos C2560",
  "Apeos C3060",
  "Apeos C3070",
  "Apeos C325 dw",
  "Apeos C325 z",
  "Apeos C3570",
  "Apeos C4570",
  "Apeos C5570",
  "ApeosPrint C325 dw",
  "Apeos 4620 SX",
  "Apeos 4620 SZ",
  "Assist Handle",
  "Booklet Maker Unit for Finisher-B",
  "Cabinet",
  "Cable Assy-ffc LED MBL3",
  "Data Overwrite Kit",
  "Data Overwrite Kit (HW)",
  "Drum Cartridge",
  "Drum Cartridge (K)",
  "Drum Cartridge WW",
  "Drum Cartridge (YMCK)",
  "Embedded IC Card Reader B",
  "Fax Kit 3 1byte",
  "Fax Kit 3 (Type-C) 1",
  "Fax Kit 3 (Type-C) 2",
  "Fusing Unit (220V)(WW)",
  "Finisher-A2",
  "Finisher-B4",
  "Finisher-C4 2/4 Hole Punch",
  "Finisher-C4 with Booklet Maker 2/4 Hole Punch",
  "Finisher Installation Kit for Finisher-B",
  "Finisher Installation Kit for Finisher-C",
  "Folder Unit CD3",
  "High Capacity Feeder B1",
  "High Capacity Toner Cartridge (C)",
  "High Capacity Toner Cartridge (K)",
  "High Capacity Toner Cartridge (M)",
  "High Capacity Toner Cartridge (Y)",
  "IC CARD READER B",
  "Multi-Language Font Kit",
  "Secondary Ethernet Kit",
  "Standard Capacity Toner Cartridge (C)",
  "Standard Capacity Toner Cartridge (K)",
  "Standard Capacity Toner Cartridge (M)",
  "Standard Capacity Toner Cartridge (Y)",
  "Toner Cartridge - Black *High Capacity",
  "Toner Cartridge - Black *Standard Capacity",
  "Toner Cartridge - Cyan *High Capacity",
  "Toner Cartridge - Cyan *Standard Capacity",
  "Toner Cartridge - Magenta *High Capacity",
  "Toner Cartridge - Magenta *Standard Capacity",
  "Toner Cartridge - Yellow *High Capacity",
  "Toner Cartridge - Yellow *Standard Capacity",
  "Transport Assv-Regi No",
  "Toner Cartridge C WW",
  "Toner Cartridge K WW",
  "Toner Cartridge M WW",
  "Toner Cartridge Y WW",
  "Transport Unit H4",
  "Tray Module",
  "USB-Hub",
  "Waste Toner Bottle",
  "Waste Toner Container",
  "Waste Toner Container 1",
  "Wireless Network Kit 2",
  "Pipe ASSY-DISP FB",
];

export const brandOptions = ["Promark", "White Label"];
export const dispatchFromOptions = [
  "Patna",
  "Bareilly",
  "Ranchi",
  "Morinda",
  "Lucknow",
  "Delhi",
  "Jaipur",
  "Rajasthan",
];

export const productCode = [
  "TC101907",
  "TC101908",
  "TC101909",
  "EC104653",
  "EC104655",
  "QC100205",
  "EC103914",
  "EC104830",
  "EC104835",
  "EC104837",
  "EC104643",
  "EC104202",
  "EC104713",
  "EC104208",
  "E9100212",
  "CT203939",
  "CT203940",
  "CT203941",
  "CT203942",
  "CT351388",
  "CWAA1056",
  "TL200766",
  "TL200767",
  "TL200768",
  "CT351389",
  "CT203952",
  "TL301186",
  "TL301184",
  "TL301182",
  "EL300952",
  "CT203804",
  "CT203805",
  "CT203806",
  "CT203807",
  "CT203808",
  "CT203809",
  "CT203810",
  "CT203811",
  "CT351282",
  "CWAA0980",
  "TC101841",
  "TC101843",
  "TC101844",
  "TC101850",
  "TM100241",
  "TM100242",
  "QC100223",
  "QC100238",
  "EC104194",
  "EC104195",
  "EC104240",
  "QC100234",
  "QC100236",
  "QC100213",
  "EC104241",
  "QC100214",
  "EC104714",
  "EM100588",
  "EC104741",
  "EC104742",
  "EC104193",
  "EC104718",
  "EC104209",
  "CT203767",
  "CT203768",
  "CT203769",
  "CT203770",
  "CT351364",
  "CT203936",
  "CT351387",
  "CWAA1044",
  "CWAA0728",
  "TC101905",
  "EC104855",
  "EC104854",
  "EC104856",
  "EC104866",
  "EC104204",
  "CT204009",
  "CT204010",
  "CT204011",
  "CT204012",
  "CT204013",
  "CT204014",
  "CT204015",
  "CT204016",
  "CT351410",
  "CWAA1068",
  "TL301263",
  "TL301264",
  "EL301028",
  "EL301029",
  "CT204229",
  "CT204231",
  "CT351436",
  "117K 50711",
  "CWAA1058",
  "859K01543",
  "052K15520",
];
