export const productOptions = [
  "Others",
  "Chairs",
  "Tables",
  "Sheet Metal",
  "Desking",
  "Solid Wood",
  "Boards",
  "Lab Tables",
];
export const statesAndCities = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Jaganathpuram",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Kurnool",
    "Rajahmundry",
    "Nellore",
    "Anantapur",
    "Kadapa",
    "Srikakulam",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Proddatur",
    "Machilipatnam",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Tawang",
    "Ziro",
    "Pasighat",
    "Bomdila",
    "Naharlagun",
    "Roing",
    "Aalo",
    "Tezu",
    "Changlang",
    "Khonsa",
    "Yingkiong",
    "Daporijo",
    "Seppa",
  ],
  Assam: [
    "Agartala",
    "Tripura",
    "Guwahati",
    "Dibrugarh",
    "Jorhat",
    "Silchar",
    "Tezpur",
    "Tinsukia",
    "Nagaon",
    "Sivasagar",
    "Barpeta",
    "Goalpara",
    "Karimganj",
    "Lakhimpur",
    "Diphu",
    "Golaghat",
    "Kamrup",
  ],
  Bihar: [
    "Chapra",
    "Siwan",
    "Gopalganj",
    "Bettiah",
    "Motihari",
    "Sitamarhi",
    "Sheohar",
    "Darbhanga",
    "Madhubani",
    "Samastipur",
    "Vaishali",
    "Muzaffarpur",
    "Madhepura",
    "Khagaria",
    "Begusrai",
    "Lakhisrai",
    "Munger",
    "Jamui",
    "Banka",
    "Bhagalpur",
    "Katihar",
    "Purnia",
    "Araria",
    "Kishanganj",
    "Patna",
    "Bhojpur/Arah",
    "Buxar",
    "Rohtas/Sasaram",
    "Kaimur",
    "Aurangabad",
    "Arwal",
    "Jehanabad",
    "Nawada",
    "Sheikhpura",
    "Gaya",
    "Barh",
    "Nalanda",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Korba",
    "Bhilai",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Dhamtari",
    "Kawardha",
    "Mahasamund",
    "Kondagaon",
    "Bijapur",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Sanguem",
    "Canacona",
    "Quepem",
    "Valpoi",
    "Sanquelim",
    "Curchorem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Morbi",
    "Nadiad",
    "Porbandar",
    "Mehsana",
    "Bharuch",
    "Navsari",
    "Surendranagar",
  ],
  Haryana: [
    "Bahadurgarh",
    "Charkhi Dadri",
    "Panchkula",
    "Gurugram",
    "Faridabad",
    "Tohna",
    "Panipat",
    "Ambala",
    "Hisar",
    "Palwal",
    "Rohtak",
    "Karnal",
    "Bhiwani",
    "Kaithal",
    "Kurukshetra",
    "Sonipat",
    "Jhajjar",
    "Jind",
    "Fatehabad",
    "Pehowa",
    "Pinjore",
    "Rewari",
    "Yamunanagar",
    "Sirsa",
    "Dabwali",
    "Narwana",
    "Mahendragarh",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul and Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una",
  ],
  Jharkhand: [
    "Ranchi",
    "Koderma",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Palamu",
    "Gumla",
    "Lohardaga",
    "Dumka",
    "Chatra",
    "Pakur",
    "Jamtara",
    "Simdega",
    "Sahibganj",
    "Godda",
    "Latehar",
    "Khunti",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Kalaburagi",
    "Ballari",
    "Davangere",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Vijayapura",
    "Chikkamagaluru",
    "Hassan",
    "Mandya",
    "Raichur",
    "Bidar",
    "Bagalkot",
    "Chitradurga",
    "Kolar",
    "Gadag",
    "Yadgir",
    "Haveri",
    "Dharwad",
    "Ramanagara",
    "Chikkaballapur",
    "Kodagu",
    "Koppal",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kannur",
    "Alappuzha",
    "Thrissur",
    "Kottayam",
    "Palakkad",
    "Ernakulam",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Kollam",
    "Kasaragod",
    "Punalur",
    "Varkala",
    "Changanassery",
    "Kayani",
    "Kizhakkambalam",
    "Perumbavoor",
    "Muvattupuzha",
    "Attingal",
    "Vypin",
    "North Paravur",
    "Adoor",
    "Cherthala",
    "Mattancherry",
    "Fort Kochi",
    "Munroe Island",
  ],
  "Madhya Pradesh": [
    "Shajapur",
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Ratlam",
    "Satna",
    "Dewas",
    "Murwara (Katni)",
    "Chhindwara",
    "Rewa",
    "Burhanpur",
    "Khandwa",
    "Bhind",
    "Shivpuri",
    "Vidisha",
    "Sehore",
    "Hoshangabad",
    "Itarsi",
    "Neemuch",
    "Chhatarpur",
    "Betul",
    "Mandsaur",
    "Damoh",
    "Singrauli",
    "Guna",
    "Ashok Nagar",
    "Datia",
    "Mhow",
    "Pithampur",
    "Shahdol",
    "Seoni",
    "Mandla",
    "Tikamgarh",
    "Raisen",
    "Narsinghpur",
    "Morena",
    "Barwani",
    "Rajgarh",
    "Khargone",
    "Anuppur",
    "Umaria",
    "Dindori",
    "Sheopur",
    "Alirajpur",
    "Jhabua",
    "Sidhi",
    "Harda",
    "Balaghat",
    "Agar Malwa",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Thane",
    "Satara",
    "Latur",
    "Chandrapur",
    "Jalgaon",
    "Bhiwandi",
    "Shirdi",
    "Akola",
    "Parbhani",
    "Raigad",
    "Washim",
    "Buldhana",
    "Nanded",
    "Yavatmal",
    "Beed",
    "Amravati",
    "Kalyan",
    "Dombivli",
    "Ulhasnagar",
    "Nagothane",
    "Vasai",
    "Virar",
    "Mira-Bhayandar",
    "Dhule",
    "Sangli",
    "Wardha",
    "Ahmednagar",
    "Pandharpur",
    "Malegaon",
    "Osmanabad",
    "Gondia",
    "Baramati",
    "Jalna",
    "Hingoli",
    "Sindhudurg",
    "Ratnagiri",
    "Palghar",
    "Ambarnath",
    "Badlapur",
    "Taloja",
    "Alibaug",
    "Murbad",
    "Karjat",
    "Pen",
    "Newasa",
  ],
  Manipur: [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Bishnupur",
    "Kakching",
    "Senapati",
    "Ukhrul",
    "Tamenglong",
    "Jiribam",
    "Moreh",
    "Noney",
    "Pherzawl",
    "Kangpokpi",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Cherrapunjee",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Mawkyrwat",
    "Resubelpara",
    "Mairang",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Saiha",
    "Lawngtlai",
    "Mamit",
    "Hnahthial",
    "Khawzawl",
    "Saitual",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Mon",
    "Zunheboto",
    "Phek",
    "Longleng",
    "Kiphire",
    "Peren",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Puri",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Jeypore",
    "Angul",
    "Dhenkanal",
    "Keonjhar",
    "Kendrapara",
    "Jagatsinghpur",
    "Paradeep",
    "Bargarh",
    "Rayagada",
    "Koraput",
    "Nabarangpur",
    "Kalahandi",
    "Nuapada",
    "Phulbani",
    "Balangir",
    "Sundargarh",
  ],
  Punjab: [
    "Amritsar",
    "Bathinda",
    "Barnala",
    "Derabassi",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Lodhipur",
    "Ferozepur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "S.A.S. Nagar",
    "Sangrur",
    "Shaheed Bhagat Singh Nagar",
    "Sri Muktsar Sahib",
    "Tarn Taran",
  ],
  Rajasthan: [
    "Sri Ganganagar",
    "Hanumangarh",
    "Churu",
    "Jhunjhunu",
    "Sikar",
    "Deedwana Kuchaman",
    "Nagaur",
    "Bikaner",
    "Phalodi",
    "Jaisalmer",
    "Barmer",
    "Balotra",
    "Jodhpur",
    "Pali",
    "Jalore",
    "Sirohi",
    "Udaipur",
    "Salumber",
    "Dungarpur",
    "Banswara",
    "Pratapgarh",
    "Chittorgarh",
    "Rajsamand",
    "Bhilwara",
    "Ajmer",
    "Beawar",
    "Tonk",
    "Bundi",
    "Kota",
    "Baran",
    "Jhalawar",
    "Jaipur",
    "Dausa",
    "Sawai Madhopur",
    "Karauli",
    "Dholpur",
    "Bharatpur",
    "Deeg",
    "Alwar",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Pelling",
    "Geyzing",
    "Mangan",
    "Rangpo",
    "Jorethang",
    "Yuksom",
    "Ravangla",
    "Lachen",
    "Lachung",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thanjavur",
    "Tuticorin",
    "Dindigul",
    "Cuddalore",
    "Kancheepuram",
    "Nagercoil",
    "Kumbakonam",
    "Karur",
    "Sivakasi",
    "Namakkal",
    "Tiruppur",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Ramagundam",
    "Siddipet",
    "Adilabad",
    "Nalgonda",
    "Mancherial",
    "Kothagudem",
    "Zaheerabad",
    "Miryalaguda",
    "Bhongir",
    "Jagtial",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Kamalpur",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Sonamura",
    "Melaghar",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Bulandshahr",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahar",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Greater Noida",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kushi Nagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffar Nagar",
    "Noida",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharth Nagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Rishikesh",
    "Mussoorie",
    "Almora",
    "Pithoragarh",
    "Haldwani",
    "Rudrapur",
    "Bageshwar",
    "Champawat",
    "Uttarkashi",
    "Roorkee",
    "Tehri",
    "Lansdowne",
  ],
  "West Bengal": [
    "Kolkata",
    "Garia",
    "Darjeeling",
    "Siliguri",
    "Howrah",
    "Asansol",
    "Durgapur",
    "Malda",
    "Cooch Behar",
    "Haldia",
    "Kharagpur",
    "Raiganj",
    "Bardhaman",
    "Jalpaiguri",
    "Chandannagar",
    "Kalimpong",
    "Alipurduar",
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Havelock Island",
    "Diglipur",
    "Neil Island",
    "Car Nicobar",
    "Little Andaman",
    "Long Island",
    "Mayabunder",
    "Campbell Bay",
    "Rangat",
    "Wandoor",
  ],
  Chandigarh: [
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 7",
    "Sector 8",
    "Sector 9",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Amli",
    "Kachigam",
    "Naroli",
    "Vapi",
    "Marwad",
    "Samarvarni",
    "Kawant",
  ],
  Delhi: [
    "New Delhi",
    "Rani Bagh",
    "Shalimar Bagh",
    "Tilak Nagar",
    "Hari Nagar Dadb",
    "Hari Nagar",
    "Maya Puri",
    "Alaknanda",
    "Old Delhi",
    "Dwarka",
    "Rohini",
    "Karol Bagh",
    "Lajpat Nagar",
    "Saket",
    "Vasant Kunj",
    "Janakpuri",
    "Mayur Vihar",
    "Shahdara",
    "Preet Vihar",
    "Pitampura",
    "Chanakyapuri",
    "Narela",
    "Mehrauli",
    "Najafgarh",
    "Okhla",
    "Tilak Nagar",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],
  Ladakh: [
    "Leh",
    "Kargil",
    "Diskit",
    "Padum",
    "Nubra",
    "Tangtse",
    "Sankoo",
    "Zanskar",
    "Nyoma",
    "Turtuk",
    "Hanle",
  ],
  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Amini",
    "Andrott",
    "Kalpeni",
    "Kadmat",
    "Chetlat",
    "Bitra",
    "Bangaram",
  ],
  Puducherry: [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam",
    "Villianur",
    "Bahour",
    "Oulgaret",
    "Ariyankuppam",
    "Nettapakkam",
  ],
};

export const orderTypeOptions = [
  "B2G",
  "B2C",
  "B2B",
  "Demo",
  "Replacement",
  "Stock Out",
];

/** Maps stored DB values to their display labels */
export const ORDER_TYPE_DISPLAY = {
  "Stock Out": "Stock",
};

/** Maps stored DB values to their display labels for dispatch status */
export const DISPATCH_STATUS_DISPLAY = {
  "Not Dispatched": "Pending Dispatched",
};

export const companyOptions = [
  "Promark",
  "Foxmate",
  "Promine",
  "Primus",
  "Lead Systems Incorporatio",
];

export const paymentMethodOptions = ["Cash", "NEFT", "RTGS", "Cheque"];
export const paymentTermsOptions = [
  "100% Advance",
  "Partial Advance",
  "Credit",
];
export const salesPersonlist = [
  "Abhay Pratap Singh",
  "Abhay Bhardwaj",
  "Abhayjit Sekhon",
  "Ajay Kumar",
  "Amarjeet Singh",
  "Anirban Syam",
  "Arif Khan",
  "Arwinder Singh",
  "Ashwani Kumar",
  "Bachan Pal",
  "Deepak saini",
  "Parth Bhardwaj",
  "Global",
  "Gursewak Singh",
  "Gem Team",
  "Gurnam Bhullar",
  "Heena Mehra",
  "Harpeet Singh",
  "J P Sharma",
  "Jagan Lal",
  "Jyoti Rani",
  "Javvad Akram",
  "Jashanpreet",
  "Jai Srivastava",
  "Kulwinder Singh",
  "Manish CS Lange",
  "Madeeha Hasan",
  "Manjit Singh Chowhan",
  "Mayank Goutam",
  "Mukul Kubba",
  "Monika",
  "Muskan",
  "Nadeem Khan",
  "Narinder Singh",
  "Parmjeet Singh",
  "Pranab Bhattacharjee",
  "Priyanka Rajput",
  "Pitamber Sharma",
  "Priya Sharma",
  "Pihu Juneja",
  "Payal Narayan",
  "Piyush Chopra",
  "PS Brar",
  "Purnendu Kumar",
  "Raj Bahadur Singh",
  "Rajeev Kanda",
  "Rajeev Kumar Singh",
  "Rajeev Pal Singh",
  "Riya Rana",
  "Ramkumar Singh",
  "Ranbeer Kaur",
  "Rachit Arya",
  "Rahul",
  "Rohit Kumar Tiwari",
  "Ritik Poddar",
  "Shadab Khan",
  "Sahil Gupta",
  "Sahiba",
  "Savir Khan",
  "Shri Kant",
  "Swati Sood",
  "Sidhant Oberai",
  "Sidhant Prajapati",
  "Sukhjinder Pal Singh",
  "Sunil Kukkar",
  "Sunil Kumar Singh",
  "Surbhi Chugh",
  "Sushil Kumar",
  "Sukhvir Singh",
  "Savita Mamgain",
  "Sonali Dalal",
  "Srishti Yadav",
  "Sushant Dutta",
  "Seema",
  "Vinay Bhardwaj",
  "Vageesh Bhardwaj",
  "Varun Budhiraja",
  "Vaseem Khan",
  "Vishal Angra"
];

export const Reportinglist = [
  "Abhay Pratap Singh",
  "Abhayjit Sekhon",
  "Amarjeet Singh",
  "Arwinder Singh",
  "Ashwani Kumar",
  "Bachan Pal",
  "Gem Team",
  "Harpeet Singh",
  "J P Sharma",
  "Manjit Singh Chowhan",
  "PS Brar",
  "Priya Sharma",
  "Purnendu Kumar",
  "Raj Bahadur Singh",
  "Rajeev Kanda",
  "Rajeev Kumar Singh",
  "Rajeev Pal Singh",
  "Sahil Gupta",
  "Susheel Kumar",
  "Sukhvir Singh",
  "Savir Khan",
  "Sukhjinder Pal Singh",
  "Sunil Kukkar",
  "Surbhi Chugh",
  "Sushil Kumar",
  "Varun Budhiraja",
  "Vaseem Khan",
];

export const modelNoOptions = ["AT"];
export const brandOptions = ["Promark", "White Label"];
export const dispatchFromOptions = [
  "Patna",
  "Bareilly",
  "Ranchi",
  "Morinda",
  "Lucknow",
  "Delhi",
  "Jaipur",
  "Rajasthan",
];
