export const statesAndCities = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Jaganathpuram",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Kurnool",
    "Rajahmundry",
    "Nellore",
    "Anantapur",
    "Kadapa",
    "Srikakulam",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Proddatur",
    "Machilipatnam",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Tawang",
    "Ziro",
    "Pasighat",
    "Bomdila",
    "Naharlagun",
    "Roing",
    "Aalo",
    "Tezu",
    "Changlang",
    "Khonsa",
    "Yingkiong",
    "Daporijo",
    "Seppa",
  ],
  Assam: [
    "Agartala",
    "Tripura",
    "Guwahati",
    "Dibrugarh",
    "Jorhat",
    "Silchar",
    "Tezpur",
    "Tinsukia",
    "Nagaon",
    "Sivasagar",
    "Barpeta",
    "Goalpara",
    "Karimganj",
    "Lakhimpur",
    "Diphu",
    "Golaghat",
    "Kamrup",
  ],
  Bihar: [
    "Chapra",
    "Siwan",
    "Gopalganj",
    "Bettiah",
    "Motihari",
    "Sitamarhi",
    "Sheohar",
    "Darbhanga",
    "Madhubani",
    "Samastipur",
    "Vaishali",
    "Muzaffarpur",
    "Madhepura",
    "Khagaria",
    "Begusrai",
    "Lakhisrai",
    "Munger",
    "Jamui",
    "Banka",
    "Bhagalpur",
    "Katihar",
    "Purnia",
    "Araria",
    "Kishanganj",
    "Patna",
    "Bhojpur/Arah",
    "Buxar",
    "Rohtas/Sasaram",
    "Kaimur",
    "Aurangabad",
    "Arwal",
    "Jehanabad",
    "Nawada",
    "Sheikhpura",
    "Gaya",
    "Barh",
    "Nalanda",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Korba",
    "Bhilai",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Dhamtari",
    "Kawardha",
    "Mahasamund",
    "Kondagaon",
    "Bijapur",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Sanguem",
    "Canacona",
    "Quepem",
    "Valpoi",
    "Sanquelim",
    "Curchorem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Morbi",
    "Nadiad",
    "Porbandar",
    "Mehsana",
    "Bharuch",
    "Navsari",
    "Surendranagar",
  ],
  Haryana: [
    "Ch. Dadri",
    "Mahendragarh",
    "Nuh",
    "Palwal",
    "Gohana",
    "Bahadurgarh",
    "Gurugram",
    "Faridabad",
    "Panchkula",
    "Panipat",
    "Ambala",
    "Hisar",
    "Rohtak",
    "Karnal",
    "Bhiwani",
    "Kaithal",
    "Kurukshetra",
    "Sonipat",
    "Jhajjar",
    "Jind",
    "Fatehabad",
    "Pehowa",
    "Pinjore",
    "Rewari",
    "Yamunanagar",
    "Sirsa",
    "Dabwali",
    "Narwana",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul and Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una",
  ],
  Jharkhand: [
    "Koderma",
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Palamu",
    "Gumla",
    "Lohardaga",
    "Dumka",
    "Chatra",
    "Pakur",
    "Jamtara",
    "Simdega",
    "Sahibganj",
    "Godda",
    "Latehar",
    "Khunti",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Kalaburagi",
    "Ballari",
    "Davangere",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Vijayapura",
    "Chikkamagaluru",
    "Hassan",
    "Mandya",
    "Raichur",
    "Bidar",
    "Bagalkot",
    "Chitradurga",
    "Kolar",
    "Gadag",
    "Yadgir",
    "Haveri",
    "Dharwad",
    "Ramanagara",
    "Chikkaballapur",
    "Kodagu",
    "Koppal",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kannur",
    "Alappuzha",
    "Thrissur",
    "Kottayam",
    "Palakkad",
    "Ernakulam",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Kollam",
    "Kasaragod",
    "Punalur",
    "Varkala",
    "Changanassery",
    "Kayani",
    "Kizhakkambalam",
    "Perumbavoor",
    "Muvattupuzha",
    "Attingal",
    "Vypin",
    "North Paravur",
    "Adoor",
    "Cherthala",
    "Mattancherry",
    "Fort Kochi",
    "Munroe Island",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Shajapur",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Ratlam",
    "Satna",
    "Dewas",
    "Murwara (Katni)",
    "Chhindwara",
    "Rewa",
    "Burhanpur",
    "Khandwa",
    "Bhind",
    "Shivpuri",
    "Vidisha",
    "Sehore",
    "Hoshangabad",
    "Itarsi",
    "Neemuch",
    "Chhatarpur",
    "Betul",
    "Mandsaur",
    "Damoh",
    "Singrauli",
    "Guna",
    "Ashok Nagar",
    "Datia",
    "Mhow",
    "Pithampur",
    "Shahdol",
    "Seoni",
    "Mandla",
    "Tikamgarh",
    "Raisen",
    "Narsinghpur",
    "Morena",
    "Barwani",
    "Rajgarh",
    "Khargone",
    "Anuppur",
    "Umaria",
    "Dindori",
    "Sheopur",
    "Alirajpur",
    "Jhabua",
    "Sidhi",
    "Harda",
    "Balaghat",
    "Agar Malwa",
  ],
  Maharashtra: [
    "Mumbai",
    "Gadchiroli",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Thane",
    "Satara",
    "Latur",
    "Chandrapur",
    "Jalgaon",
    "Bhiwandi",
    "Shirdi",
    "Akola",
    "Parbhani",
    "Raigad",
    "Washim",
    "Buldhana",
    "Nanded",
    "Yavatmal",
    "Beed",
    "Amravati",
    "Kalyan",
    "Dombivli",
    "Ulhasnagar",
    "Nagothane",
    "Vasai",
    "Virar",
    "Mira-Bhayandar",
    "Dhule",
    "Sangli",
    "Wardha",
    "Ahmednagar",
    "Pandharpur",
    "Malegaon",
    "Osmanabad",
    "Gondia",
    "Baramati",
    "Jalna",
    "Hingoli",
    "Sindhudurg",
    "Ratnagiri",
    "Palghar",
    "Ambarnath",
    "Badlapur",
    "Taloja",
    "Alibaug",
    "Murbad",
    "Karjat",
    "Pen",
    "Newasa",
  ],
  Manipur: [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Bishnupur",
    "Kakching",
    "Senapati",
    "Ukhrul",
    "Tamenglong",
    "Jiribam",
    "Moreh",
    "Noney",
    "Pherzawl",
    "Kangpokpi",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Cherrapunjee",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Mawkyrwat",
    "Resubelpara",
    "Mairang",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Saiha",
    "Lawngtlai",
    "Mamit",
    "Hnahthial",
    "Khawzawl",
    "Saitual",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Mon",
    "Zunheboto",
    "Phek",
    "Longleng",
    "Kiphire",
    "Peren",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Puri",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Jeypore",
    "Angul",
    "Dhenkanal",
    "Keonjhar",
    "Kendrapara",
    "Jagatsinghpur",
    "Paradeep",
    "Bargarh",
    "Rayagada",
    "Koraput",
    "Nabarangpur",
    "Kalahandi",
    "Nuapada",
    "Phulbani",
    "Balangir",
    "Sundargarh",
  ],
  Punjab: [
    "Amritsar",
    "Bathinda",
    "Barnala",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Ferozepur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "S.A.S. Nagar", // Sahibzada Ajit Singh Nagar
    "Sangrur",
    "Shaheed Bhagat Singh Nagar", // Nawanshahr
    "Sri Muktsar Sahib",
    "Tarn Taran",
  ],
  Rajasthan: [
    "Sri Ganganagar",
    "Hanumangarh",
    "Churu",
    "Jhunjhunu",
    "Sikar",
    "Deedwana Kuchaman",
    "Nagaur",
    "Bikaner",
    "Phalodi",
    "Jaisalmer",
    "Barmer",
    "Balotra",
    "Jodhpur",
    "Pali",
    "Jalore",
    "Sirohi",
    "Udaipur",
    "Salumber",
    "Dungarpur",
    "Banswara",
    "Pratapgarh",
    "Chittorgarh",
    "Rajsamand",
    "Bhilwara",
    "Ajmer",
    "Beawar",
    "Tonk",
    "Bundi",
    "Kota",
    "Baran",
    "Jhalawar",
    "Jaipur",
    "Dausa",
    "Sawai Madhopur",
    "Karauli",
    "Dholpur",
    "Bharatpur",
    "Deeg",
    "Alwar",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Pelling",
    "Geyzing",
    "Mangan",
    "Rangpo",
    "Jorethang",
    "Yuksom",
    "Ravangla",
    "Lachen",
    "Lachung",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thanjavur",
    "Tuticorin",
    "Dindigul",
    "Cuddalore",
    "Kancheepuram",
    "Nagercoil",
    "Kumbakonam",
    "Karur",
    "Sivakasi",
    "Namakkal",
    "Tiruppur",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Ramagundam",
    "Siddipet",
    "Adilabad",
    "Nalgonda",
    "Mancherial",
    "Kothagudem",
    "Zaheerabad",
    "Miryalaguda",
    "Bhongir",
    "Jagtial",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Kamalpur",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Sonamura",
    "Melaghar",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi",
    "Amroha",
    "Auraiya",
    "Ayodhya",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahar",
    "Chandauli",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj",
    "Kaushambi",
    "Kushi Nagar",
    "Lakhimpur Kheri",
    "Lalitpur",
    "Lucknow",
    "Maharajganj",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffar Nagar",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli",
    "Shravasti",
    "Siddharth Nagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Rishikesh",
    "Mussoorie",
    "Almora",
    "Pithoragarh",
    "Haldwani",
    "Rudrapur",
    "Bageshwar",
    "Champawat",
    "Uttarkashi",
    "Roorkee",
    "Tehri",
    "Lansdowne",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Cooch Behar",
    "Dakshin Dinajpur",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Bardhaman",
    "Purba Bardhaman",
    "Paschim Medinipur",
    "Purba Medinipur",
    "Purulia",
    "South 24 Parganas",
    "Uttar Dinajpur",
    "Sundarban",
    "Ichhamati",
    "Basirhat",
    "Ranaghat",
    "Bishnupur",
    "Jangipur",
    "Baharampur"
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Havelock Island",
    "Diglipur",
    "Neil Island",
    "Car Nicobar",
    "Little Andaman",
    "Long Island",
    "Mayabunder",
    "Campbell Bay",
    "Rangat",
    "Wandoor",
  ],
  Chandigarh: [
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 7",
    "Sector 8",
    "Sector 9",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
    "Sector 48",
    "Sector 49",
    "Sector 50",
    "Sector 51",
    "Sector 52",
    "Sector 53",
    "Sector 54",
    "Sector 55",
    "Sector 56",
    "Sector 63",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Amli",
    "Kachigam",
    "Naroli",
    "Vapi",
    "Marwad",
    "Samarvarni",
    "Kawant",
  ],
  Delhi: [
    "New Delhi",
    "Old Delhi",
    "Dwarka",
    "Rohini",
    "Karol Bagh",
    "Lajpat Nagar",
    "Saket",
    "Vasant Kunj",
    "Janakpuri",
    "Mayur Vihar",
    "Shahdara",
    "Preet Vihar",
    "Pitampura",
    "Chanakyapuri",
    "Narela",
    "Mehrauli",
    "Najafgarh",
    "Okhla",
    "Tilak Nagar",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],

  Ladakh: [
    "Leh",
    "Kargil",
    "Diskit",
    "Padum",
    "Nubra",
    "Tangtse",
    "Sankoo",
    "Zanskar",
    "Nyoma",
    "Turtuk",
    "Hanle",
  ],
  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Amini",
    "Andrott",
    "Kalpeni",
    "Kadmat",
    "Chetlat",
    "Bitra",
    "Bangaram",
  ],
  Puducherry: [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam",
    "Villianur",
    "Bahour",
    "Oulgaret",
    "Ariyankuppam",
    "Nettapakkam",
  ],
};

export const productOptions = [
  {
    name: "No Requirement",
    sizes: ["Not Applicable"],
    specifications: ["No specific requirement"],
  },
  {
    name: "IFPD",
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch", "110 inch"],
    specifications: [
      "Android 9, 4GB RAM, 32GB ROM",
      "Android 8, 4GB RAM, 32GB ROM",
      "Android 11, 4GB RAM, 32GB ROM",
      "Android 11, 8GB RAM, 128GB ROM",
      "Android 13, 4GB RAM, 32GB ROM",
      "Android 13, 8GB RAM, 128GB ROM",
      "Android 13, 8GB RAM, 128GB ROM Inbuilt Camera",
      "Android 14, 8GB RAM, 128GB ROM",
      "Android 14, 8GB RAM, 128GB ROM Inbuilt Camera",
    ],
  },
  {
    name: "OPS",
    sizes: ["N/A"],
    specifications: [
      // i5 6th Gen
      "i5 6th Gen, 8GB RAM, 256GB ROM",
      "i5 6th Gen, 8GB RAM, 512GB ROM",
      "i5 6th Gen, 8GB RAM, 1TB ROM",
      "i5 6th Gen, 16GB RAM, 256GB ROM",
      "i5 6th Gen, 16GB RAM, 512GB ROM",
      "i5 6th Gen, 16GB RAM, 1TB ROM",
      // i5 7th Gen
      "i5 7th Gen, 8GB RAM, 256GB ROM",
      "i5 7th Gen, 8GB RAM, 512GB ROM",
      "i5 7th Gen, 8GB RAM, 1TB ROM",
      "i5 7th Gen, 16GB RAM, 256GB ROM",
      "i5 7th Gen, 16GB RAM, 512GB ROM",
      "i5 7th Gen, 16GB RAM, 1TB ROM",
      // i5 8th Gen
      "i5 8th Gen, 8GB RAM, 256GB ROM",
      "i5 8th Gen, 8GB RAM, 512GB ROM",
      "i5 8th Gen, 8GB RAM, 1TB ROM",
      "i5 8th Gen, 16GB RAM, 256GB ROM",
      "i5 8th Gen, 16GB RAM, 512GB ROM",
      "i5 8th Gen, 16GB RAM, 1TB ROM",
      // i5 11th Gen
      "i5 11th Gen, 8GB RAM, 256GB ROM",
      "i5 11th Gen, 8GB RAM, 512GB ROM",
      "i5 11th Gen, 8GB RAM, 1TB ROM",
      "i5 11th Gen, 16GB RAM, 256GB ROM",
      "i5 11th Gen, 16GB RAM, 512GB ROM",
      "i5 11th Gen, 16GB RAM, 1TB ROM",
      // i5 12th Gen
      "i5 12th Gen, 8GB RAM, 256GB ROM",
      "i5 12th Gen, 8GB RAM, 512GB ROM",
      "i5 12th Gen, 8GB RAM, 1TB ROM",
      "i5 12th Gen, 16GB RAM, 256GB ROM",
      "i5 12th Gen, 16GB RAM, 512GB ROM",
      "i5 12th Gen, 16GB RAM, 1TB ROM",
      // i7 4th Gen
      "i7 4th Gen, 8GB RAM, 256GB ROM",
      "i7 4th Gen, 8GB RAM, 512GB ROM",
      "i7 4th Gen, 8GB RAM, 1TB ROM",
      "i7 4th Gen, 16GB RAM, 256GB ROM",
      "i7 4th Gen, 16GB RAM, 512GB ROM",
      "i7 4th Gen, 16GB RAM, 1TB ROM",
      // i7 5th Gen
      "i7 5th Gen, 8GB RAM, 256GB ROM",
      "i7 5th Gen, 8GB RAM, 512GB ROM",
      "i7 5th Gen, 8GB RAM, 1TB ROM",
      "i7 5th Gen, 16GB RAM, 256GB ROM",
      "i7 5th Gen, 16GB RAM, 512GB ROM",
      "i7 5th Gen, 16GB RAM, 1TB ROM",
      // i7 6th Gen
      "i7 6th Gen, 8GB RAM, 256GB ROM",
      "i7 6th Gen, 8GB RAM, 512GB ROM",
      "i7 6th Gen, 8GB RAM, 1TB ROM",
      "i7 6th Gen, 16GB RAM, 256GB ROM",
      "i7 6th Gen, 16GB RAM, 512GB ROM",
      "i7 6th Gen, 16GB RAM, 1TB ROM",
      // i7 7th Gen
      "i7 7th Gen, 8GB RAM, 256GB ROM",
      "i7 7th Gen, 8GB RAM, 512GB ROM",
      "i7 7th Gen, 8GB RAM, 1TB ROM",
      "i7 7th Gen, 16GB RAM, 256GB ROM",
      "i7 7th Gen, 16GB RAM, 512GB ROM",
      "i7 7th Gen, 16GB RAM, 1TB ROM",
      // i7 8th Gen
      "i7 8th Gen, 8GB RAM, 256GB ROM",
      "i7 8th Gen, 8GB RAM, 512GB ROM",
      "i7 8th Gen, 8GB RAM, 1TB ROM",
      "i7 8th Gen, 16GB RAM, 256GB ROM",
      "i7 8th Gen, 16GB RAM, 512GB ROM",
      "i7 8th Gen, 16GB RAM, 1TB ROM",
      // i7 9th Gen
      "i7 9th Gen, 8GB RAM, 256GB ROM",
      "i7 9th Gen, 8GB RAM, 512GB ROM",
      "i7 9th Gen, 8GB RAM, 1TB ROM",
      "i7 9th Gen, 16GB RAM, 256GB ROM",
      "i7 9th Gen, 16GB RAM, 512GB ROM",
      "i7 9th Gen, 16GB RAM, 1TB ROM",
      // i7 10th Gen
      "i7 10th Gen, 8GB RAM, 256GB ROM",
      "i7 10th Gen, 8GB RAM, 512GB ROM",
      "i7 10th Gen, 8GB RAM, 1TB ROM",
      "i7 10th Gen, 16GB RAM, 256GB ROM",
      "i7 10th Gen, 16GB RAM, 512GB ROM",
      "i7 10th Gen, 16GB RAM, 1TB ROM",
      // i7 11th Gen
      "i7 11th Gen, 8GB RAM, 256GB ROM",
      "i7 11th Gen, 8GB RAM, 512GB ROM",
      "i7 11th Gen, 8GB RAM, 1TB ROM",
      "i7 11th Gen, 16GB RAM, 256GB ROM",
      "i7 11th Gen, 16GB RAM, 512GB ROM",
      "i7 11th Gen, 16GB RAM, 1TB ROM",
      // i7 12th Gen
      "i7 12th Gen, 8GB RAM, 256GB ROM",
      "i7 12th Gen, 8GB RAM, 512GB ROM",
      "i7 12th Gen, 8GB RAM, 1TB ROM",
      "i7 12th Gen, 16GB RAM, 256GB ROM",
      "i7 12th Gen, 16GB RAM, 512GB ROM",
      "i7 12th Gen, 16GB RAM, 1TB ROM",
    ],
  },
  {
    name: "Digital Podium",
    sizes: ["Standard"],
    specifications: [
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 2 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
    ],
  },
  {
    name: "Advance Digital Podium",
    sizes: ["Front Display 32inch"],
    specifications: [
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 2 COOLER MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 1 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
      'MINI PC 21.5" TOUCH DISPLAY, AMP. 70 WATT 30 W, 2 SPEAKER, 2 HANDHELD MIC, 1 GOOSENECK MIC, VISUALIZER',
    ],
  },
  {
    name: "Audio Podium",
    sizes: ["Full"],
    specifications: ["N/A"],
  },
  {
    name: "Audio-Visual Solutions",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },

  {
    name: "Kiosk",
    sizes: ["22 inch", "32 inch", "43 inch", "55 inch", "65 inch"],
    specifications: [
      "Touch Andriod 13/4/32",
      "Non-Touch Andriod 13/4/32",
      "Windows 10 16/256/i5",
    ],
  },
  {
    name: "PTZ Camera",
    sizes: ["N/A"],
    specifications: [
      "Non-Voice Tracking-Full HD",
      "FHD Voice Tracking 20X",
      "4K Auto Tracking 12X",
      "4K Gesture Tracking 10X",
      "PRO 208H: 10X, 4K, 30fps, Voice Tracking, Gesture Control",
      "PRO 3008: 20X, Voice Tracking, Gesture Control, 30fps, USB 3.0",
      "PRO 500V: 20X, 4K, Voice Tracking, Gesture Control, 60fps, USB 3.0",
    ],
  },
  {
    name: "Document Camera",
    sizes: ["N/A"],
    specifications: [
      "Hydraulic Wall Mount Visualizer",
      "Non-Hydraulic Wall Mount Visualizer",
      "Slim Portable Visualizer",
      "Table Top Portable Visualizer",
      "Visualizer",
    ],
  },
  {
    name: "UPS",
    sizes: ["Standard"],
    specifications: [
      "1 KVA",
      "2 KVA",
      "3 KVA",
      "4 KVA",
      "5 KVA",
      "6 KVA",
      "7 KVA",
      "8 KVA",
      "9 KVA",
      "10 KVA",
      "Offline UPS",
      "Online UPS",
    ],
  },
  {
    name: "Wallmount Kit",
    sizes: ["55 inch", "65 inch", "75 inch", "86 inch", "98 inch"],
    specifications: ["Standard"],
  },
  {
    name: "Furniture",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "CCTV",
    sizes: ["Standard"],
    specifications: ["N/A"],
  },
  {
    name: "Stylus Pen",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Sliding Shutter",
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch"],
    specifications: [
      "Common",
      "White & Red Dispaly Boards",
      "White & Green Dispaly Boards",
      "White & Blue Dispaly Boards",
      "N/A",
    ],
  },
  {
    name: "3 Cup Speaker",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Single Cup Mike PRO BTD3",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "2 Cup Mike PRO BTD7",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "4 Cup Mike PRO AI5W",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },

  {
    name: "Microphone",
    sizes: ["N/A"],
    specifications: [
      "Handheld Collar Mic",
      "Goose Neck Mic",
      "Collar/Lapel Mic",
    ],
  },
  {
    name: "Keyboard",
    sizes: ["N/A"],
    specifications: ["Wireless", "Wired"],
  },
  {
    name: "Mouse",
    sizes: ["N/A"],
    specifications: ["Wireless", "Wired"],
  },
  {
    name: "Interactive White Board",
    sizes: ["82 inch"],
    specifications: ["Ceramic", "Non-Ceramic"],
  },
  {
    name: "Floor Stand",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Notice Board",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Visualizer",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "PTZ Camera - Full HD Voice Tracking",
    sizes: ["N/A"],
    specifications: ["FHD Voice Tracking"],
  },
  {
    name: "PTZ Camera - 4K Auto Tracking",
    sizes: ["N/A"],
    specifications: ["4K Auto Tracking"],
  },
  {
    name: "Web Cam",
    sizes: ["N/A"],
    specifications: [
      "Full HD Non-AI Featured",
      "4K AI Featured",
      "4K Auto Tracking",
    ],
  },
  {
    name: "Web Cam PRO MINI2",
    sizes: ["N/A"],
    specifications: ["Stanadard"],
  },
  {
    name: "Bluetooth Microphone",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "UPS - Offline",
    sizes: ["N/A"],
    specifications: ["Offline UPS"],
  },
  {
    name: "UPS - Online",
    sizes: ["N/A"],
    specifications: ["Online UPS"],
  },
  {
    name: "UPS Cabinet",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "SD Card",
    sizes: ["N/A"],
    specifications: ["8GB", "16GB", "32GB", "64GB", "128GB"],
  },
  {
    name: "Casing",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Fitting Accessories",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "HDMI Cable",
    sizes: ["N/A"],
    specifications: ["Standard", "4K"],
  },
  {
    name: "White Board",
    sizes: ["3x4", "4x6", "4x8", "4x10", "4x12"],
    specifications: ["Ceramic", "Non-Magnetic", "Magnetic (Rc)"],
  },
  {
    name: "C-type Cable",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Fujifilm-Printer",
    sizes: ["N/A"],
    specifications: [
      "Color Printer",
      "Monochrome Printer",
      "Black and White Printer",
      "Multifunction Color Printer",
      "Multifunction Monochrome Printer",
      "Multifunction Black and White Printer",
      "CABLE ASSY-FFC LED MBL3 (117K 50711)",
      "FUSING UNIT (220V)(WW) (CWAA1058)",
      "TRANSPORT ASSY-REGI MO (859K 01543)",
    ],
  },
  {
    name: "Google TV",
    sizes: ["43 inch", "50 inch", "55 inch"],
    specifications: ["4GB RAM / 32GB ROM 4K"],
  },
  {
    name: "Wriety Software",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Ceiling Mount Kit",
    sizes: ["Standard"],
    specifications: ["Projector Ceiling Mount", "PTZ Ceiling Mount"],
  },
  {
    name: "Almirah Type Shutter",
    sizes: ["65 inch", "75 inch", "86 inch", "98 inch"],
    specifications: ["Plain", "White Boards", "Green Boards"],
  },
  {
    name: "Aicharya",
    sizes: ["N/A"],
    specifications: ["Standard"],
  },
  {
    name: "Logo",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Microphones",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "E-Share License",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "PRO Share Software",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "E Share Software",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "DMS Software",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Videobar PRO UP4C",
    sizes: ["N/A"],
    specifications: ["Standard"],
  },
  {
    name: "Battery Bank",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Rack & Interlink",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Green Board",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Wooden Podium",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Writing Board",
    sizes: ["4X8", "4X10", "4X12"],
    specifications: ["Green", "White"],
  },
  {
    name: "LED Video Wall",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "4K Video Bar",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Microsoft Office 2016 Licensed",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Windows 11 Licensed",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Embibe Content",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "SSD",
    sizes: ["N/A"],
    specifications: ["256GB", "512GB", "1TB"],
  },
  {
    name: "RAM",
    sizes: ["N/A"],
    specifications: ["8GB", "16GB"],
  },
  {
    name: "Video Conferencing Camera",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "CBSE Content",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "ICSE Content",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "PA System Speakers",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Red Board",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Promark Stickers",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Bluetooth Speaker",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "3 Cup Conference Speaker",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Conference Setup-Delegate Room",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Content",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Flex",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Wireless Speakerphone - Two Pair",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Remote",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Educational Software",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Hydraulic Bracket",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Desktop PC Monitor",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Home Theatre",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Digital Audio Processor",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Projector",
    sizes: ["N/A"],
    specifications: ["Long Throw", "Short Throw", "Ultra Long Throw"],
  },
  {
    name: "LED TV",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Digital Podium Controller",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Amplifier Mic Receiver",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Wireless Mic Receiver",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Projector Screen",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Speakerphone",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "IT Catalog",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "AI Charya Podium",
    sizes: ["N/A"],
    specifications: ["Standard"],
  },
  {
    name: "4 Pole C Curve MCB",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Extension Mic",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Mike Wireless",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Advance Podium",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Speaker & Mic",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Document Visualizer",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Black Metal Body Electronic Lectern",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "LED Monitor",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Document Camera Wall Mounted",
    sizes: ["N/A"],
    specifications: [
      "Hydraulic Wall Mount Visualizer",
      "Non-Hydraulic Wall Mount Visualizer",
    ],
  },
  {
    name: "SLV Mic",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Bubble Roll",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
  {
    name: "Wrapping Roll",
    sizes: ["N/A"],
    specifications: ["N/A"],
  },
];
